BookstoreProject/Controllers/BooksController.cs
using BookstoreProject.Models;
using BookstoreProject.Services.Contracts;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authorization.Infrastructure;
using Microsoft.AspNetCore.Mvc;

namespace BookstoreProject.Controllers
{
    [Authorize(Roles = "Admin")]
    public class BooksController : Controller
    {
        private readonly IBooksService _booksService;

        public BooksController(IBooksService service)
        { 
            _booksService = service;
        }
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            List<Book> books = await _booksService.GetBooksFromGoogleBooksAPI();
            return View(books);
        }
        
     
        public async Task<IActionResult> Delete(string id)
		{
			List<Book> books = await _booksService.GetBooksFromGoogleBooksAPI();
			Book book = books.FirstOrDefault(b => b.Id == id);
			if (book == null)
			{
				return NotFound();
			}

			return View(book);
		}
       
        public async Task<IActionResult> Edit(string id)
		{
			List<Book> books = await _booksService.GetBooksFromGoogleBooksAPI();
			Book book = books.FirstOrDefault(b => b.Id == id);
			if (book == null)
			{
				return NotFound();
			}

			return View(book);
		}
        [AllowAnonymous]
		public async Task<IActionResult> Details(string id)
        {
            List<Book> books = await _booksService.GetBooksFromGoogleBooksAPI();
            Book book = books.FirstOrDefault(b => b.Id == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }
        
    }
}

BookstoreProject/Controllers/CartController.cs
using BookstoreProject.Models;
using BookstoreProject.Services.Contracts;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;

namespace BookstoreProject.Controllers
{
	[Authorize]
	public class CartController : Controller
	{
        private readonly ICartService _cartService;
        
        public CartController(ICartService cartService)
        {
            _cartService = cartService;
        }

		public IActionResult Index()
		{
			Cart cart = _cartService.ViewCart();
			return View(cart);
		}

		public IActionResult AddToCart(string id)
        {
            _cartService.AddToCart(id);
            return RedirectToAction("Index");
        }
		public IActionResult RemoveFromCart(string id)
		{
			_cartService.RemoveFromCart(id);
			return RedirectToAction("Index");
		}

		public IActionResult ClearCart()
		{
			_cartService.ClearCart();
			return RedirectToAction("Index");
		}

	}
}

BookstoreProject/Controllers/StoreController.cs
using BookstoreProject.Models;
using BookstoreProject.Services.Contracts;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using X.PagedList;

namespace BookstoreProject.Controllers
{
    public class StoreController : Controller
    {

        private readonly IBooksService _booksService;
        public StoreController(IBooksService service)
        {
            _booksService = service;
        }
        public async Task<IActionResult> Index(string search,int? page)
        {
            List<Book> books = await _booksService.GetBooksFromGoogleBooksAPI();

            if (!string.IsNullOrEmpty(search))
            {
                books = books.Where(b => b.Title.Contains(search) || b.Authors.Contains(search)).ToList();
            }
            int pageNumber = page ?? 1;  
            int pageSize = 20;            
            IPagedList<Book> pagedBooks = books.ToPagedList(pageNumber, pageSize);     
            return View(pagedBooks);
        }


		public async Task<IActionResult> Details(string id)
		{
			List<Book> books = await _booksService.GetBooksFromGoogleBooksAPI();
			Book book = books.FirstOrDefault(b => b.Id == id);
			if (book == null)
			{
				return NotFound();
			}

			return View(book);
		}

	}
}

BookstoreProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookstoreProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BookstoreProject.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/fontawesome/css/all.css" />
    <link rel="stylesheet" href="~/css/myStyle.css" />
    
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-warning border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Store" asp-action="Index">BookStore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Store" asp-action="Index">Store</a>
                        </li>    
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Books" asp-action="Index">Books</a>
                        </li>
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="ListAllRoles">Roles</a>
                            </li>
                        }  
                    </ul>
                    <a id="cart-link" class="nav-link text-dark float-right" asp-area="" asp-controller="Cart" asp-action="Index">
                        <i id="cart-icon" class="fa-solid fa-cart-shopping"></i>
                    </a>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
   
    <footer class="border-bottom footer">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-md-6">
                    <h5>About Us</h5>
                    <ul class="list-unstyled">
                        <li><a asp-area="" asp-controller="Home" asp-action="Privacy">Our Vision</a></li>
                        <li><a asp-area="" asp-controller="Home" asp-action="Terms">Our Mission</a></li>
                        <li><a asp-area="" asp-controller="Contact" asp-action="Index">Advices</a></li>
                    </ul>
                </div>
                
                <div class="col-lg-4 col-md-6">
                    <h5>Open Library</h5>
                    <ul class="list-unstyled">
                        <li><a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy Policy</a></li>
                        <li><a asp-area="" asp-controller="Home" asp-action="Terms">Terms of Service</a></li>
                        <li><a asp-area="" asp-controller="Contact" asp-action="Index">Contact Us</a></li>
                    </ul>
                </div>
                <div class="col-lg-4">
                    <h5>Follow Us</h5>
                    <ul class="list-inline">
                        <li class="list-inline-item"><a href="https://www.facebook.com"><i class="fab fa-facebook-f"></i></a></li>
                        <li class="list-inline-item"><a href="https://www.twitter.com"><i class="fab fa-twitter"></i></a></li>
                        <li class="list-inline-item"><a href="https://www.instagram.com"><i class="fab fa-instagram"></i></a></li>
                        <li class="list-inline-item"><a href="https://www.pinterest.com"><i class="fab fa-pinterest"></i></a></li>
                    </ul>
                </div>

            </div>
           
            <p class="text-center">&copy; 2023 - BookstoreProject</p>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>